In [0]:
import torch

Реализация градиентного спуска

In [0]:
x = torch.tensor(
   [[1, 2, 3, 4], 
    [5, 6, 7, 8],
    [9, 10, 11, 12]], requires_grad=True, dtype=torch.float, device='cuda:0')

In [0]:
x

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]], device='cuda:0', requires_grad=True)

In [0]:
function = 10 * (x ** 2).sum()

In [0]:
function

tensor(6500., device='cuda:0', grad_fn=<MulBackward0>)

Расчет градиента

In [0]:
function.backward()


In [0]:
print(x.grad)

tensor([[ 20.,  40.,  60.,  80.],
        [100., 120., 140., 160.],
        [180., 200., 220., 240.]], device='cuda:0')


In [0]:
print(function.grad_fn.next_functions[0][0])

Градиент для функции $f(w) = \prod\limits_{i,j}{log_{e}(log_{e}({w_{i,j} + 7}}))$ в точке $w = [[5, 10], [1, 2]]$

In [0]:
w = torch.tensor([[5, 10], [1, 2]], dtype=torch.float, device='cuda:0', requires_grad=True)

In [0]:
w

tensor([[ 5., 10.],
        [ 1.,  2.]], device='cuda:0', requires_grad=True)

In [0]:
function1 = (w + 7).log().log().prod()

In [0]:
function1

tensor(0.5463, device='cuda:0', grad_fn=<ProdBackward0>)

In [0]:
function1.backward()

In [0]:
w.grad

tensor([[0.0201, 0.0109],
        [0.0449, 0.0351]], device='cuda:0')

Заканчиваем реализацию градиентного спуска. Обновление тензора

In [0]:
alpha = 0.001

In [0]:
x.data -= alpha * x.grad

Для обновления тензора, у которого можно вычислить градиент, следует обновлять не тензор, по которому можно вычислить градиент, а сами данные, которые лежат в этом тензоре.
Таким образом по этой операции не будет считаться градиент. 
У x.data "requires_grad = False"

In [0]:
x

tensor([[ 0.9600,  1.9200,  2.8800,  3.8400],
        [ 4.8000,  5.7600,  6.7200,  7.6800],
        [ 8.6400,  9.6000, 10.5600, 11.5200]], device='cuda:0',
       requires_grad=True)

Обнуляем градиент. Т.к. в PyTorch градиент накапливается (хз зачем).

In [0]:
x.grad.zero_()

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], device='cuda:0')